site_name: docs
copyright: © 2025 AxonOps Limited. All rights reserved.
dev_addr: '0.0.0.0:8000'

theme:
  name: 'material'
  favicon: '/img/favicon.ico'
  logo: '/img/axonops_logo.png'
  language: 'en'
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - announce.dismiss
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy

extra:
  analytics:
    provider: google
    property: UA-69443414-2
  consent:
    title: Cookie Consent
    description:
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
  generator: false
  homepage: https://axonops.com
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/axonops/
      name: Linkedin - AxonOps
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/AxonOpsSoftware
      name: X - AxonOps
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC33iN3vrQmpYOXTSWzWr5Ng
      name: Youtube - AxonOps

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - codehilite:
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: true
      css_style:
        width: "100%"
        height: "15vw"
  - glightbox:
      width: 100%
      height: auto
      zoomable: true
      skip_classes:
        - skip-lightbox

extra_javascript:
  - javascripts/extra.js

not_in_nav: |
  dynamic_pages

nav:
  - Home: index.md
  
  # - Get Started:
  - AxonOps Cloud:
    - Editions: 
      - Developer Edition: 'editions/developer_edition.md'
      - Starter Edition: 'editions/starter_edition.md'
      - Enterprise Edition: 'editions/enterprise_edition.md'

    - Setup:
      - AxonOps Cloud account: 'get_started/cloud.md'
      - AxonOps Cloud agents: 'get_started/agent_setup.md'

  - AxonOps Self-Hosted:
    - Get Started: get_started/getting_started.md

    - Security:
      - Firewall Rules: firewall/overview.md 

    - Installing AxonOps:
      - Elasticsearch: 'installation/elasticsearch/install.md'
      
      - Cassandra as Metrics store: 'installation/axon-server/metricsdatabase.md'

      - AxonOps Server: 'installation/axon-server/axonserver_install.md'
      - AxonOps Dashboard: 'installation/axon-dash/install.md'
      - AxonOps Agent: 'installation/agent/install.md'
      - Kubernetes: 'installation/kubernetes/index.md'
      - System Requirements: system-requirements/index.md

    - Authentication:
      - LDAP: 'authentication/ldap.md' 
      
    - Developer:
      - Quickstart - Docker: 'get_started/docker.md'
      
    - Compatibility:
      - Interoperability matrix: 'installation/compat_matrix/compat_matrix.md'

    
  - Using AxonOps:
    - Cluster Overview:
      - Overview: 'cluster/cluster-overview.md'
    
    - Monitoring:
      - Monitoring Overview: 'monitoring/overview.md'
      - Service Checks: 'monitoring/servicechecks/overview.md'
      - 'Metrics in Grafana': 'monitoring/grafana/grafana.md'
      - Logs & Events: 'monitoring/logsandevents/logsandevents.md'

    - Cassandra:
      - Metrics Dashboard:
        - Cassandra: 'monitoring/metricsdashboards/cassandra.md'
        - Metrics Query Syntax: 'monitoring/metricsdashboards/querysyntax.md'

      - Operations:
        - Repair: 'operations/cassandra/repair.md'
        - Rolling Restart: 'operations/cassandra/rollingrestart/overview.md'

      - Backup:
        - Overview: 'operations/cassandra/backup/overview.md'
        - Remote Backups:
          - Overview: 'operations/cassandra/backup/remote.md'
          - Local Storage: 'operations/cassandra/backup/local_storage.md'
          - AWS S3: 'operations/cassandra/backup/aws_s3.md'
          - Generic S3: 'operations/cassandra/backup/generic_s3.md'
          - Google Cloud Storage: 'operations/cassandra/backup/gcs.md'
          - Azure Blob Storage: 'operations/cassandra/backup/azure_blob.md'
          - SSH/SFTP: 'operations/cassandra/backup/ssh_sftp.md'
      
      - Restore:
        - Overview: 'operations/cassandra/restore/overview.md'
        - Single node: 'operations/cassandra/restore/restore-node-same-ip.md'
        - Single node with a different IP address: 'operations/cassandra/restore/restore-node-different-ip.md'
        - Whole cluster: 'operations/cassandra/restore/restore-cluster-same-ip.md'
        - Whole cluster with changed IP addresses: 'operations/cassandra/restore/restore-cluster-different-ips.md'
        - Restore to a different cluster: 'operations/cassandra/restore/restore-different-cluster.md'
      
      - Point-in-time Restore:
        - Overview: pitr/overview.md
        - Configure Commitlog Archiving: pitr/configuration.md
        - Restore from Point-in-Time: pitr/restore.md
      
    - Kafka:
      # - Operations:
      #   - Rolling Restart: 'operations/kafka/rollingrestart/overview.md'
      - Metrics Dashboard:
        - Kafka: 'monitoring/metricsdashboards/kafka.md'
        - Metrics Query Syntax: 'monitoring/metricsdashboards/querysyntax_kafka.md'

      - Brokers: 
        - Overview : kafka/brokers/overview.md
      
      - Topics: 
        - Overview: kafka/topics/overview.md
        - Create Topic: kafka/topics/create_topic.md
        - Configure Topic: kafka/topics/configure_topic.md
      
      - ACL: 
        - Overview: kafka/acl/overview.md
        - Create ACL: kafka/acl/create_acl.md
        # - Configure ACL: kafka/acl/configure_acl.md
        # - Delete ACL: kafka/acl/delete_acl.md

      - Consumers: 
        - Overview: kafka/consumers/overview.md
    
    - Notification Integrations:
      - Overview : 'integrations/overview.md'
      - PagerDuty: 'integrations/pagerduy-integration.md'
      - Slack: 'integrations/slack-integration.md'
      - Microsoft Teams: 'integrations/microsoft-teams-integration.md'
      - ServiceNow: 'integrations/servicenow-integration.md'
      - SMTP / Email: 'integrations/email-integration.md'
      - Log Files: 'integrations/log-file-integration.md'
      
    - How-to:
      - Setup Alert Rules: how-to/setup-alert-rules.md
      - Setup Default Routing: how-to/default-routing.md
      - Setup Log Collection: how-to/setup-log-collection.md
      - Re-use an existing host ID: how-to/reuse-host-id.md
    
  - AxonOps Workbench:
    - Cassandra: 
      # - 'Overview' : workbench/cassandra/cassandra.md
      - License: workbench/cassandra/license.md 

  # - Release Notes:
  #   - Release notes: 'release_notes/releases.md'
