site_name: docs
copyright: © 2024 AxonOps Limited. All rights reserved.
dev_addr: '0.0.0.0:8000'

theme:
  name: 'material'
  favicon: '/img/favicon.ico'
  logo: '/img/axonops_logo.png'
  language: 'en'
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - announce.dismiss
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy

extra:
  analytics:
    provider: google
    property: UA-69443414-2
  consent:
    title: Cookie Consent
    description:
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
  generator: false
  homepage: https://axonops.com
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/axonops/
      name: Linkedin - AxonOps
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/AxonOpsSoftware
      name: X - AxonOps
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC33iN3vrQmpYOXTSWzWr5Ng
      name: Youtube - AxonOps

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - codehilite:
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.superfences
  - tables

plugins:
  - search
  - glightbox:
      width: 100%
      height: auto
      zoomable: true
      skip_classes:
        - skip-lightbox

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  
  # - Get Started:
  - AxonOps Cloud: 
    - Editions: 
      - Developer Edition: 'editions/developer_edition.md'
      - Starter Edition: 'editions/starter_edition.md'
      - Enterprise Edition: 'editions/enterprise_edition.md'

    - Setup:
      - AxonOps Cloud account: 'get_started/cloud.md'
      - AxonOps Cloud agents: 'get_started/agent_setup.md'

  - AxonOps Self-Hosted:
    - Starter:
      - AxonOps Server: 'installation-starter/axon-server/axonserver_install.md'
      - AxonOps Dashboard: 'installation-starter/axon-dash/install.md'
      - AxonOps Agent: 'installation-starter/cassandra-agent/install.md'
      - AxonOps Agent in Docker: 'installation-starter/cassandra-agent/docker.md'
      - System Requirements: system-requirements/developer.md

    - Enterprise:
      - AxonOps Server: 'installation/axon-server/axonserver_install.md'
      - Securing Elasticsearch: 'installation/axon-server/securing_elastic.md'
      - Cassandra as Metrics database: 'installation/axon-server/metricsdatabase.md'
      - AxonOps Dashboard: 'installation/axon-dash/install.md'
      - Configure Nginx: 'installation/axon-dash/configure_nginx.md'
      - AxonOps Agent: 'installation/cassandra-agent/install.md'
      - Kubernetes: 'installation/kubernetes/index.md'
      - System Requirements: system-requirements/index.md

    - Developer:
      - Quickstart - Docker: 'get_started/docker.md'
      
    - Compatibility:
      - Interoperability matrix: 'installation/compat_matrix/compat_matrix.md'
    
  - Using AxonOps:
    - Cluster Overview:
      - Overview: 'cluster/cluster-overview.md'

    - Monitoring:
      - Monitoring Overview: 'monitoring/overview.md'
      - Service Checks: 'monitoring/servicechecks/overview.md'
      - Metrics Dashboard:
          - Cassandra: 'monitoring/metricsdashboards/cassandra.md'
          - Metrics Query Syntax: 'monitoring/metricsdashboards/querysyntax.md'
      - Logs & Events: 'monitoring/logsandevents/logsandevents.md'

    - Notification Integrations:
      - Overview : 'integrations/overview.md'
      - PagerDuty Integration: 'integrations/pagerduy-integration.md'
      - Slack Integration: 'integrations/slack-integration.md'
      - Microsoft Teams: 'integrations/microsoft-teams-integration.md'
      - ServiceNow: 'integrations/servicenow-integration.md'
      - Email Integration: 'integrations/email-integration.md'

    - Operations:
      - Repair: 'operations/cassandra/repair.md'
      - Rolling Restart: 'operations/cassandra/rollingrestart/overview.md'
    - Backup:
      - Overview: 'operations/cassandra/backup/overview.md'
      - Remote Backups:
        - Overview: 'operations/cassandra/backup/remote.md'
        - AWS S3: 'operations/cassandra/backup/aws_s3.md'
    - Restore:
      - Overview: 'operations/cassandra/restore/overview.md'
      - Single node: 'operations/cassandra/restore/restore-node-same-ip.md'
      - Single node with a different IP address: 'operations/cassandra/restore/restore-node-different-ip.md'
      - Whole cluster: 'operations/cassandra/restore/restore-cluster-same-ip.md'
      - Whole cluster with changed IP addresses: 'operations/cassandra/restore/restore-cluster-different-ips.md'
      - Restore to a different cluster: 'operations/cassandra/restore/restore-different-cluster.md'
    - Point-in-time Restore:
      - Overview: pitr/overview.md
      - Configure Commitlog Archiving: pitr/configuration.md
      - Restore from Point-in-Time: pitr/restore.md
      
    - How-to:
      - Setup Alert Rules: how-to/setup-alert-rules.md
      - Setup Default Routing: how-to/default-routing.md
      - Setup Log Collection: how-to/setup-log-collection.md
      - Re-use an existing host ID: how-to/reuse-host-id.md
    
  - AxonOps Workbench:
    - Cassandra: 
      # - 'Overview' : workbench/cassandra/cassandra.md
      - License: workbench/cassandra/license.md 

  # - Release Notes:
  #   - Release notes: 'release_notes/releases.md'
