site_name: Documentation
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/bg_logo.png'
  language: 'en'
  
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
       
  - toc:
      permalink: true
plugins:
    - search

nav:
    - Introduction: index.md

    - Overview:
        - 'Motivation': 'overview/motivation.md'
        - 'Architecture': 'overview/architecture.md'

    - Installation:
        - Axonops Server: 'installation/server.md'
        - Axonops Dashboard:
            - 'Installing on Ubuntu/Debian': 'installation/gui/installing-ubuntu.md'
            - 'Installing on Centos/Redhat': 'installation/gui/installing-centos.md'
        - Axonops Agents:
            - 'Installing on Ubuntu/Debian': 'installation/agents/installing-ubuntu.md'
            - 'Installing on Centos/Redhat': 'installation/agents/installing-centos.md'
        - Axonops Cassandra Agent: 'installation/cassandra-agent.md'

    - Configuration:
        - 'AxonOps Server Configuration': 'configuration/server-configuration.md'
        - 'AxonOps Agent Configuration': 'configuration/agent-configuration.md'
        - 'AxonOps GUI Service Configuration': 'configuration/axondash.md'

    - Using AxonOps:
        - Cluster Overview:
            - 'Cluster Overview': 'cluster/cluster-overview.md'

        - Monitoring:
            - Health Checks:
                - 'Health Checks Overview': 'monitoring/healthchecks/overview.md'
                - 'Health Checks Configurations': 'monitoring/healthchecks/configurations.md'
                - 'Health Checks Alerting': 'monitoring/healthchecks/alerting.md'
            - Metrics Dashboard:
                - Cassandra:
                    - 'Overview': 'monitoring/metricsdashboards/cassandra/overview.md'
                    - 'Cassandra Metrics': 'monitoring/metricsdashboards/cassandra/cassandra.md'
                    - 'Metrics Alerting Configurations': 'monitoring/metricsdashboards/cassandra/alerting.md'
        
        - Notification Integrations:
                - 'Overview' : 'integrations/overview.md'
                - 'PagerDuty Integration': 'integrations/pagerduy-integration.md'
                - 'Slack Integration': 'integrations/slack-integration.md'
                - 'Email Integration': 'integrations/email-integration.md'

        - Operations:
            - Cassandra: 
                - Repair:
                    - 'Overview': 'operations/cassandra/repair/overview.md'
                    - 'Cassandra Repair Configurations': 'operations/cassandra/repair/configurations.md'
                - Backups:
                    - 'Overview': 'operations/cassandra/backup/overview.md'
                    - 'Cassandra Backup Configurations': 'operations/cassandra/backup/configurations.md'

    - How-to:
            - 'Setup Alert Rules': how-to/setup-alert-rules.md
            - 'Setup Healthcheks': how-to/setup-healthcheks.md
            - 'Setup Default Routing': 'how-to/default-routing.md'
            - 'Setup Backup-Restore Notifications': 'how-to/backup-restore-notifications.md'
            - 'Setup Dashboards-Global Integrations': 'how-to/setup-dashboards-global-integrations.md'


#    - GUI:
#        - 'Overview': 'gui-overview.md'
#        - 'Features': 'gui-features.md'
#        - 'Setup': 'gui-setup.md'
   
#    - Cassandra:
#        - 'Dashboards': 'cassandra-dashboards.md'
#        - Operations:
#            - 'Repair': 'cassandra-repair.md'
#            - 'Backup and Restore': 'cassandra-backup-and-restore.md'
#    - Kafka:
        
