site_name: AxonOps Documentation
copyright: © 2021 digitalis.io All Rights Reserved

theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/axonops_logo.svg'
  language: 'en'

extra:
    analytics:
        provider: google
        property: UA-69443414-2
    consent:
        title: Cookie Consent
        description:
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
    generator: false

extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - codehilite:
      guess_lang: False

  - toc:
      permalink: true
plugins:
    - search

nav:
    - Introduction: index.md

    - Overview:
        - 'Motivation': 'overview/motivation.md'
        - 'Architecture': 'overview/architecture.md'
        # TODO: - - 'AxonOps Cloud': 'overview/axonops-cloud.md'
        # TODO: - 'AxonOps Enterprise': 'overview/axonops-enterprise.md'

    - Installation:
        - AxonOps Server:
            - 'Installing on Ubuntu/Debian': 'installation/axon-server/ubuntu.md'
            - 'Installing on Centos/Redhat': 'installation/axon-server/centos.md'
        - AxonOps GUI Server: 'installation/axon-dash/install.md'
        #- AxonOps Agent: 'installation/axon-agent/install.md'
        - AxonOps Cassandra Agent: 'installation/cassandra-agent/install.md'
        - Compatibility matrix: 'installation/compat_matrix/compat_matrix.md'
        - Kubernetes: 'installation/kubernetes/minikube.md'

    - Using AxonOps:
        - Cluster Overview:
            - 'Overview': 'cluster/cluster-overview.md'

        - Monitoring:
            - 'Monitoring Overview': 'monitoring/overview.md'
            - Service Checks: 'monitoring/servicechecks/overview.md'
            - Metrics Dashboard:
                - 'Cassandra': 'monitoring/metricsdashboards/cassandra.md'
            - Logs & Events: 'monitoring/logsandevents/logsandevents.md'

        - Notification Integrations:
                - 'Overview' : 'integrations/overview.md'
                - 'PagerDuty Integration': 'integrations/pagerduy-integration.md'
                - 'Slack Integration': 'integrations/slack-integration.md'
                - 'ServiceNow': 'integrations/servicenow-integration.md'
                - 'Email Integration': 'integrations/email-integration.md'

        - Operations:
            - Cassandra:
                - Repair: 'operations/cassandra/repair.md'
                - Backups:
                    - 'Overview': 'operations/cassandra/backup/overview.md'
                    - 'Restore': 'operations/cassandra/restore/overview.md'
                - 'Rolling Restart': 'operations/cassandra/rollingrestart/overview.md'

    - How-to:
            - 'Setup Alert Rules': how-to/setup-alert-rules.md
            # - 'Setup Service Checks': how-to/setup-servicechecks.md
            - 'Setup Log Collection': how-to/setup-log-collection.md
            # - 'Setup Default Routing': 'how-to/default-routing.md'
            # - 'Setup Backup-Restore Notifications': 'how-to/backup-restore-notifications.md'
            # - 'Setup Dashboards-Global Integrations': 'how-to/setup-dashboards-global-integrations.md'
            - 'Re-use an existing host ID': how-to/reuse-host-id.md


#    - GUI:
#        - 'Overview': 'gui-overview.md'
#        - 'Features': 'gui-features.md'
#        - 'Setup': 'gui-setup.md'

#    - Cassandra:
#        - 'Dashboards': 'cassandra-dashboards.md'
#        - Operations:
#            - 'Repair': 'cassandra-repair.md'
#            - 'Backup and Restore': 'cassandra-backup-and-restore.md'
#    - Kafka:

