site_name: AxonOps Documentation
theme: 'material'
plugins:
    - search

nav:
    - Introduction: index.md
    - Overview:
        - 'Motivation': 'overview/motivation.md'
        - 'Architecture': 'overview/architecture.md'
    - Getting Started:
        - 'Installing Server': 'gettingstarted/installing-server.md'
        - 'Installing Agents': 'gettingstarted/installing-agents.md'
    - Configuration:
        - 'Server Configuration': 'configuration/server-configuration.md'
        - 'Agent Configuration': 'configuration/agent-configuration.md'
    - Integration:
            - 'PagerDuty Integration': 'integrations/pagerduy-integration.md'
            - 'Slack Integration': 'integrations/slack-integration.md'
            - 'Email Integration': 'integrations/email-integration.md'


#    - GUI:
#        - 'Overview': 'gui-overview.md'
#        - 'Features': 'gui-features.md'
#        - 'Setup': 'gui-setup.md'
   
#    - Cassandra:
#        - 'Dashboards': 'cassandra-dashboards.md'
#        - Operations:
#            - 'Repair': 'cassandra-repair.md'
#            - 'Backup and Restore': 'cassandra-backup-and-restore.md'
#    - Kafka:
        
