site_name: Documentation
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/bg_logo.png'
extra_css:
  - 'stylesheets/extra.css'
plugins:
    - search

nav:
    - Introduction: index.md
    - Overview:
        - 'Motivation': 'overview/motivation.md'
        - 'Architecture': 'overview/architecture.md'
    - Getting Started:
        - 'Installing Server': 'gettingstarted/installing-server.md'
        - 'Installing Agents': 'gettingstarted/installing-agents.md'
    - Configuration:
        - 'Server Configuration': 'configuration/server-configuration.md'
        - 'Agent Configuration': 'configuration/agent-configuration.md'
    - Integration: 
            - 'Overview' : integrations/overview.md
            - 'PagerDuty Integration': 'integrations/pagerduy-integration.md'
            - 'Slack Integration': 'integrations/slack-integration.md'
            - 'Email Integration': 'integrations/email-integration.md'
            
    - How-to:
            - 'Setup Alert Rules': how-to/setup-alert-rules.md
            - 'Setup Healthcheks': how-to/setup-healthcheks.md
            - 'Setup Default Routing': 'how-to/default-routing.md'
            - 'Setup Backup-Restore Notifications': 'how-to/backup-restore-notifications.md'
            - 'Setup Dashboards-Global Integrations': 'how-to/setup-dashboards-global-integrations.md'


#    - GUI:
#        - 'Overview': 'gui-overview.md'
#        - 'Features': 'gui-features.md'
#        - 'Setup': 'gui-setup.md'
   
#    - Cassandra:
#        - 'Dashboards': 'cassandra-dashboards.md'
#        - Operations:
#            - 'Repair': 'cassandra-repair.md'
#            - 'Backup and Restore': 'cassandra-backup-and-restore.md'
#    - Kafka:
        
