site_name: AxonOps Documentation
copyright: © 2020 digitalis.io All Rights Reserved
google_analytics: ['UA-69443414-2', 'docs.axonops.com']
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/axonops_logo.svg'
  language: 'en'

extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - codehilite:
      guess_lang: False

  - toc:
      permalink: true
plugins:
    - search

nav:
    - Introduction: index.md

    - Overview:
        - 'Motivation': 'overview/motivation.md'
        - 'Architecture': 'overview/architecture.md'

    - Installation:
        - AxonOps Server:
            - 'Installing on Ubuntu/Debian': 'installation/axon-server/ubuntu.md'
            - 'Installing on Centos/Redhat': 'installation/axon-server/centos.md'
        - AxonOps GUI Server: 'installation/axon-dash/install.md'
        #- AxonOps Agent: 'installation/axon-agent/install.md'
        - AxonOps Cassandra Agent: 'installation/cassandra-agent/install.md'
        - Compatibility matrix: 'installation/compat_matrix/compat_matrix.md'
        - Kubernetes: 'installation/kubernetes/minikube.md'

    - Using AxonOps: 
        - Cluster Overview:
            - 'Overview': 'cluster/cluster-overview.md'

        - Monitoring:
            - 'Monitoring Overview': 'monitoring/overview.md'
            - Service Checks: 'monitoring/servicechecks/overview.md'
            - Metrics Dashboard:
                - 'Cassandra': 'monitoring/metricsdashboards/cassandra.md'
        
        - Notification Integrations:
                - 'Overview' : 'integrations/overview.md'
                - 'PagerDuty Integration': 'integrations/pagerduy-integration.md'
                - 'Slack Integration': 'integrations/slack-integration.md'
                - 'Email Integration': 'integrations/email-integration.md'

        - Operations:
            - Cassandra: 
                - Repair: 'operations/cassandra/repair.md'
                - Backups:
                    - 'Overview': 'operations/cassandra/backup/overview.md'
                    - 'Restore': 'operations/cassandra/restore/overview.md'
                - 'Rolling Restart': 'operations/cassandra/rollingrestart/overview.md'

    - How-to:
            - 'Setup Alert Rules': how-to/setup-alert-rules.md
            # - 'Setup Service Checks': how-to/setup-servicechecks.md
            - 'Setup Log Collection': how-to/setup-log-collection.md
            # - 'Setup Default Routing': 'how-to/default-routing.md'
            # - 'Setup Backup-Restore Notifications': 'how-to/backup-restore-notifications.md'
            # - 'Setup Dashboards-Global Integrations': 'how-to/setup-dashboards-global-integrations.md'


#    - GUI:
#        - 'Overview': 'gui-overview.md'
#        - 'Features': 'gui-features.md'
#        - 'Setup': 'gui-setup.md'
   
#    - Cassandra:
#        - 'Dashboards': 'cassandra-dashboards.md'
#        - Operations:
#            - 'Repair': 'cassandra-repair.md'
#            - 'Backup and Restore': 'cassandra-backup-and-restore.md'
#    - Kafka:
        
