# SEO Meta Tags - Getting Started
description: Getting started guides for AxonOps Cloud and self-hosted deployments with step-by-step setup instructions.

meta:
  - name: keywords
    content: AxonOps getting started, quick start, setup guide, cloud deployment, agent setup
