# SEO Meta Tags - Integrations
description: AxonOps integration guides for Slack, PagerDuty, Microsoft Teams, ServiceNow, and email notifications.

meta:
  - name: keywords
    content: AxonOps integrations, Slack alerts, PagerDuty, Microsoft Teams, ServiceNow, email notifications, alerting
